# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.paths=C:/Users/svyat/AppData/Roaming/PrismLauncher/java/java-runtime-gamma,C:/Users/svyat/AppData/Roaming/PrismLauncher/java/java-runtime-delta,C:/Users/svyat/AppData/Roaming/PrismLauncher/java/java-runtime-epsilon

# Mod properties
mod_version=2.0
maven_group=ru.svyaton
archives_base_name=bookpaste

loom_version=1.14.10
loom26_version=1.15.5
loader_version=0.16.14

